# Dependencies
markdown:    redcarpet
highlighter: pygments

# Site
permalink: pretty

title:       Chris Chiles
tagline:     'tagline'
description: 'description'
url:         http://christopherchiles.com
baseurl:     /

author:
  name: 'Chris Chiles'
  url:  http://christopherchiles.com

paginate: 1

github: https://github.com/christopherchiles1
