# Dependencies
markdown:    redcarpet
highlighter: pygments

# Site
permalink: pretty

title:       Chris Chiles
description: 'Sr. Software Engineer'
url:         https://christopherchiles.com
baseurl:     https://christopherchiles.com/

author:
  name: 'Chris Chiles'
  url:  https://christopherchiles.com

paginate: 1

plugins:
  - jekyll-katex

github: https://github.com/christopherchiles1
